@startuml
'https://plantuml.com/activity-diagram-beta
!theme plain

'Crear fichero / carpeta
skinparam defaultFontName consolas
skinparam minClassWidth 100
skinparam conditionStyle inside

|Cliente|

  start
  partition Initialization {
    :Iniciar la aplicación *;
    :Iniciar la sesión *;
  }

|Aplicación|

  partition "Gestionar los ficheros" {
    :Acceder al gestor de ficheros;

    switch (Seleccionar opción)
      case ( crear fichero )
        :Crear fichero;
      case ( Crear carpeta )
        :Crear carpeta;
    endswitch
  }

stop



@enduml
