@startuml
'https://plantuml.com/activity-diagram-beta
'!theme amiga from https://raw.githubusercontent.com/plantuml/plantuml/master/themes

'Iniciar Sesión
skinparam defaultFontName consolas
skinparam minClassWidth 100
skinparam conditionStyle inside

|Cliente|

  start
  partition Initialization {
    :Iniciar la aplicación *;
    :Iniciar la sesión *;
  }

  |Aplicación|

  if (Fichero cargado) then (Si)

  else (No)
    partition "Gestionar ficheros" {
      :Acceder al gestor de ficheros;

      :Seleccionar fichero;

      :Cargar fichero;
      note right
        << Calling the method ""notification(message)""
        ====
        Al cargar un fichero se lanzara un evento
        que mostrara una notificación cuando el fichero
        este cargado en el <b>editor de monaco</b>
      end note
    }
  endif

  partition "Editor" {
    :Acceder al editor;

    :Editar contenido fichero;

    :Guardar;
    note right
      << Calling the method ""notification(message)""
      ====
      Al guardar el fichero se lanzara un evento que
      mostrara una notificación cuando el fichero se
      haya guardado y se haya confirmado por el servidor
    end note
  }
  stop


@enduml
