@startuml
'https://plantuml.com/es/use-case-diagram
'!theme amiga from https://raw.githubusercontent.com/plantuml/plantuml/master/themes
skinparam defaultFontName consolas
skinparam minClassWidth 100
skinparam conditionStyle inside
skinparam defaultTextAlignment center
skinparam linetype polyline
skinparam linetype ortho

left to right direction
'https://www.freeprojectz.com/uml-diagram/chat-application-system-sequence-diagram
actor "User" as user
rectangle THUMDER-Client {
  usecase "<<Story Case>>\nCrear una cuenta" as C_UC1
  usecase "<<Story Case>>\nIniciar sesión" as C_UC2
  usecase "<<Story Case>>\nCrear carpeta" as C_UC3.1a
  usecase "<<Story Case>>\nCrear fichero" as C_UC3.2a
  usecase "<<Story Case>>\nModificar nombre carpeta" as C_UC3.1b
  usecase "<<Story Case>>\nModificar nombre fichero"" as C_UC3.2b
  usecase "<<Story Case>>\nEliminar carpeta" as C_UC3.1c
  usecase "<<Story Case>>\nEliminar fichero" as C_UC3.2c
  usecase "<<Story Case>>\nEditar contenido fichero" as C_UC4
  usecase "<<Story Case>>\nSimular" as C_UC5
  usecase "<<Story Case>>\nMostrar estado maquina" as C_UC6
  usecase "<<Story Case>>\nActualizar estado maquina" as C_UC7
'  usecase "<<Story Case>>\nAlterar estado maquina" as C_UC9
'  usecase "<<Story Case>>\nDebug" as C_UC_Debug
}
/'
rectangle THUMDER-Server {
  usecase "Recibir" as S_UC00
  usecase "Analizar" as S_UC01
  usecase "Simular" as S_UC02
  usecase "Responder" as S_UC03
}
'/

'admin --> UC01
'admin --> UC02
user --> C_UC1
user --> C_UC2

user --> C_UC3.1a
C_UC3.1a --> C_UC3.2a
user --> C_UC3.1b
C_UC3.1b --> C_UC3.2b
user --> C_UC3.1c
C_UC3.1c --> C_UC3.2c

user --> C_UC4
user --> C_UC5
user --> C_UC6
user --> C_UC7
'user --> C_UC9
'user --> C_UC10

@enduml
