@startuml
'https://plantuml.com/sequence-diagram
/'
Action : Elementos que representas los eventos a los que responden los agentes para completar las tareas de la ontología.
Predicate : Elementos que representan las respuestas a los eventos para completar las tareas de la ontología.
'/
'autonumber
skinparam defaultFontName consolas
skinparam sequenceMessageAlign center

=== "Authentication" ==
Client ->  Server: REQUEST (AuthenticationRequest)
Client <-- Server: ACCEPT-REQUEST (AuthenticationResponse)
Client <-- Server: REJECT-REQUEST (AuthenticationResponse)

=== "CFP Simulation" ==

Client ->  Server: CFP (InitSimulation)

Client <-  Server: PROPOSE (GetFile)
Client --> Server: ACCEPT-PROPOSE (SendFile)
Client --> Server: REJECT-PROPOSE (SendFile)

group Repeat [Repeat until the last instruction]
  Client <-  Server:  PROPOSE (GetInstruction)
  Client --> Server:  ACCEPT-PROPOSAL (SendInstruction)
  Client --> Server:  REFUSE-PROPOSAL (SendInstruction)
  Client <-- Server:  INFORM (StatusMachine)
end

@enduml
