@startuml
'https://plantuml.com/class-diagram
skinparam defaultFontName consolas
skinparam defaultTextAlignment center
skinparam minClassWidth 100
skinparam conditionStyle inside
skinparam linetype polyline
skinparam linetype ortho
skinparam nodesep 50
skinparam ranksep 130
left to right direction
'!include styles.puml
hide circle

entity "Machine" as e00 {
  Breakpoints
  Registers
  Memory
}

entity "User" as e01 {

}

entity "File Manager" as e02 {
  Files
}

entity "Editor" as e03 {
  File
}

e01 ||--|| e03: Edit
e01 ||--|| e00: Simulate
e01 ||--|| e02: Manage
e02 ||--|| e03: Load file
e03 ||-up-|| e00: Load code


@enduml
