@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor User
boundary InterfaceUI
participant System
participant Server
participant Firebase

activate User
User -> InterfaceUI: Open sign in
activate InterfaceUI
User <- InterfaceUI: Show form sign in

loop Form
  loop Input user data
    User -> InterfaceUI: Input user data
    alt #LightGreen User data valid
        User <- InterfaceUI: Ok
    else #Pink User data not valid
      User <- InterfaceUI: Please repeat
    end
  end

  User -> InterfaceUI: User data

  alt #LightGreen User data successful
    InterfaceUI -> System: Create account request
    activate System
    System -> Firebase: Create account request
    activate Firebase
    System <- Firebase: Create account response
    deactivate Firebase
    alt #LightGreen successful case
        InterfaceUI <- System: Create account accepted
        User <- InterfaceUI: Create account accepted
    else #Pink Account error
        InterfaceUI <- System: Create account failure
        deactivate System
        User x<- InterfaceUI: Notification error
    end
  else #Pink
    User <- InterfaceUI: Notification error in user data
    deactivate InterfaceUI
  end

end



deactivate User

@enduml
