@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User
boundary InterfaceUI
participant System
participant Server
participant Firebase

activate User
group#Gold User login

end
User -> InterfaceUI: Open Editor
activate InterfaceUI
User <- InterfaceUI: Show Editor

InterfaceUI -> System: Analyze code
  activate System
  System -> Server: Analyze code
  activate Server
  System <- Server: Analyze code response
  deactivate Server
  InterfaceUI <- System: Analyze code response
  deactivate System

  alt #LightGreen Have error
    User <- InterfaceUI: Show error in code
  else #Pink No error in code
    User <- InterfaceUI: Show code
  end

deactivate InterfaceUI
deactivate User

@enduml
