@startuml
'https://plantuml.com/class-diagram

/'
Concept: Elementos que representan la información necesaria para representar los diferentes tipos de comunicación de la ontología.
AgentAction: Elementos que representas los eventos a los que responden los agentes para completar la comunicación de la ontología.
Predicate: Elementos que representan las respuestas a los eventos para completar la comunicación de la ontología.
'/
skinparam linetype polyline
skinparam linetype ortho


package "Concept" #DDDDDD {
  interface Concept
  abstract class Authentication implements Concept
'  annotation AuthenticationGoogle extends Authentication
'  annotation AuthenticationGithub extends Authentication
'  annotation AuthenticationEmail extends Authentication
  class AuthenticationToken extends Authentication
  class StatusMachine implements Concept
  class Instruction implements Concept
  class TreeFileManager implements Concept
}

package "AgentAction" #DDDDDD {
  interface AgentAction
  class AuthenticationRequest
  abstract class Request  extends AuthenticationRequest implements AgentAction
  class MakeFolderRequest implements Request
  class MakeFileRequest extends MakeFolderRequest
  class ModifyFolderRequest implements Request
  class ModifyFileRequest extends ModifyFolderRequest
  class DeleteFolderRequest implements Request
  class DeleteFileRequest extends DeleteFolderRequest
  class TreeFileManagerRequest implements Request
  class InstructionRequest implements Request
  class StatusMachineRequest implements Request
}

package "Predicate" #DDDDDD {
  interface Predicate
  class AuthenticationResponse
  abstract class Response extends AuthenticationResponse implements Predicate
  class MakeFolderResponse implements Response
  class MakeFileResponse extends MakeFolderResponse
  class ModifyFolderResponse implements Response
  class ModifyFileResponse extends ModifyFolderResponse
  class DeleteFolderResponse implements Response
  class DeleteFileResponse extends DeleteFolderResponse
  class TreeFileManagerResponse implements Response
  class StatusMachineResponse implements Response
  class InstructionResponse implements Response
}



@enduml
