@startuml
'https://plantuml.com/activity-diagram-beta
'!theme amiga from https://raw.githubusercontent.com/plantuml/plantuml/master/themes

'Iniciar Sesión
skinparam defaultFontName consolas
skinparam minClassWidth 100
skinparam conditionStyle inside
'skinparam defaultTextAlignment center

|Cliente|

  start
  :Iniciar la aplicación *;

  |Aplicación|

  :Iniciar la sesión *;

  partition "Gestionar ficheros" {
    :Acceder al gestor de ficheros;

    :Seleccionar fichero;
    :Cargar fichero;
    note right
      << Calling the method
      ""LaunchDefaultToast(message)""
      ====
      Al cargar un fichero se lanzara un evento
      que mostrara una notificación cuando el fichero
      este cargado en el <b>editor de monaco</b>
    end note
  }

  :Acceder Editor de ficheros;

  partition "Monaco Editor" {

    :Editar;

    split
       :Usar Tabs para guardar;
    split again
       :Usar Shortcuts para guardar;
    end split
  }
  stop



@enduml
