@startuml

    layout HBoxLayout {
        layout HBoxLayout {
            alignement: center

            component MyComponent1
            component MyComponent2
        }

        layout VBoxLayout {
            alignement: top

            component OtherComponent1
            component OtherComponent2
            OtherComponent1 ..> OtherComponent2
        }
    }

    layout GridLayout {
        column: 4
        row:    3

        ' Set this one at coordinate (2,2) of the grid
        component AnyComponent1 @2,2
    }

@enduml
