@startuml
'top to bottom direction
'!theme amiga from https://raw.githubusercontent.com/plantuml/plantuml/master/themes
skinparam defaultFontName consolas
'left to right direction
'scale 3508 width
'scale 2480 height
'scale max 1080 width
'scale max 720 height
'3508 x 2480

skinparam linetype polyline
skinparam linetype ortho

package "THUMDER" {

    package "@ngx-monaco-editor" #BBB {
      class MonacoEditor {
      }
    }
    package "@devextreme" #BBB {
      class FileManagement {
      }
    }
    package "@angular/fire" #BBB {
      class AngularFireAuth {
      }
    }

  package "@Angular" #BBB {
    interface OnInit {
      +ngOnInit(): void
    }
    interface AfterViewInit {
      +ngAfterViewInit(): void
    }
  }

  package CoreModule {
    package Machine <<Folder>> #DDDDDD {
      class Int32 <<Type>> {
          -_value: number
          +value(): number
          +value(data): number
      }
      class Float32 <<Type>> {
          -_value: number
          +value(): number
          +value(data): number
      }
      class Double64 <<Type>> {
          -_value: number
          +value(): number
          +value(data): number
      }
      class Registers {
          +PC: Int32
          +IMAR: Int32
          +IR: Int32
          +A: Int32
          +AHI: Int32
          +B: Int32
          +BHI: Int32
          +BTA: Int32
          +ALU: Int32
          +ALUHI: Int32
          +FPSR: Int32
          +DMAR: Int32
          +SDR: Int32
          +SDRHI: Int32
          +LDR: Int32
          +LDRHI: Int32
          +R: Int32[]
          +F: Float32[]
          +D: Double64[]
          +code: Int32[]
          +memory: Int32[]
      }
      class MachineService {
          -registers: Registers
          +someBusinessLogic(): void
          -{static} instance: MachineService
          +{static} getInstance(): MachineService
      }
    }
    class AuthService {
       SignIn(email, password): void
       SignUp(email, password): void
       SendVerificationMail(): Promise<Router>
       ForgotPassword(passwordResetEmail): Promise<Router>
       getIsLoggedIn(): boolean
       GoogleAuth(): boolean
       AuthLogin(): void
       SetUserData(user): AngularFirestoreDocument<any>
       SignOut(): Promise<void>
    }
    package Electron <<Folder>> #DDDDDD {
      class ElectronService {
        +ipcRenderer: Electron.IpcRenderer
        +webFrame: Electron.WebFrame
        +remote: Electron.Remote
        +childProcess: typeof childProcess
        +fs: typeof fs
        +isElectron: boolean
      }
    }
  }

  package SharedModule {
    class WebviewDirective {

    }
    class PageNotFoundComponent {
        +ngOnInit(): void
    }
  }

  package Layout {
    package Admin {
      class AdminComponent {
          -document: Document
          +ngOnInit(): void
      }
    }
    package Auth {
      class AuthComponent {
          -document: Document
          +ngOnInit(): void
      }
    }
  }

  package ComponentModule {
    class AsideLeftComponent {
        +ngOnInit(): void
        -toggleCollapseMenu(): void
    }
    class AsideRightComponent {
        +ngOnInit(): void
    }
    class BreadcrumbComponent {
      +ngOnInit(): void
      -createBreadcrumbs(): MenuItem[]
    }
    class AdminFooterComponent {
        +date: number
        +ngOnInit(): void
    }
    class AuthFooterComponent {
        +date: number
        +version: any
        +ngOnInit(): void
    }
    class MonacoEditorComponent {
        +editor: MonacoEditor
        +editorOptions_thumder: { theme: string; language: string; }
        +code_asm: string
        +oldDecoration: string[]
        +i: number
        -httpClient: HttpClient
        -monacoLoaderService: MonacoEditorLoaderService
        +ngOnInit(): void
        +onInitEditor($event: any): void
        +addNewDecorator(): void
        -registerMonacoCustomTheme(): void
    }
    class AdminNavbarComponent {
        +ngOnInit(): void
    }
    class AuthNavbarComponent {
        +navbarOpen: boolean
        -app: AppComponent
        +ngOnInit(): void
        +setNavbarOpen(): void
        +changeToSpain(): void
        +changeToEnglish(): void
    }
    class PipelinePixiComponent {
        +widthBox: number
        +widthArrowActivate: number
        +pixiContainer: any
        +pApp: Application
        +ngOnInit(): void
        +ngAfterViewInit(): void
        +bezierArrow(start?: number[], cpXY2?: number[], to?: number[]): Graphics
    }
    class XtermComponent {
        +terminalDiv: ElementRef<any>
        +data: string
        +newEvent: EventEmitter
        +terminal: Terminal
        +ngOnInit(): void
        +ngAfterViewInit(): void
        +write(text: string): void
    }
    class FileManagerComponent {
        +remoteProvider: RemoteFileSystemProvider
        +imageItemToDisplay: any
        +popupVisible: boolean
        -document: Document
        -router: Router
        +onSelectedFileOpened($event: any): void
        +ngOnInit(): void
        +height(): string | number | Function
        +onContextMenuItemClick($event: any): void
    }
  }

  package Views {
    package View {
      class LoginComponent {
          -document: Document
          +ngOnInit(): void
      }
      class RegisterComponent {
          -document: Document
          +ngOnInit(): void
      }
      class IndexComponent {
          -document: Document
          +ngOnInit(): void
      }
      class ForgotPasswordComponent {
          -document: Document
          +ngOnInit(): void
      }
      class VerifyEmailComponent {
          -document: Document
          +ngOnInit(): void
      }
      class LandingComponent {
          -document: Document
          +ngOnInit(): void
      }
    }
    package ViewAuth {
      class ProfileComponent {
          -document: Document
          +ngOnInit(): void
      }
      class IDEComponent {
          +monacoEditorComponent: MonacoEditorComponent
          +xtermComponent: XtermComponent
          -document: Document
          +ngOnInit(): void
          +iter(): void
          +toggleModal(): void
      }
      class FileManagerViewComponent {
          +remoteProvider: RemoteFileSystemProvider
          +imageItemToDisplay: any
          +popupVisible: boolean
          -document: Document
          -router: Router
          +onSelectedFileOpened($event: any): void
          +ngOnInit(): void
          +height(): string | number | Function
          +onContextMenuItemClick($event: any): void
      }
      class SidebarComponent {
          +collapseShow: string
          +ngOnInit(): void
          +toggleCollapseShow(classes: any): void
      }
      class DocsComponent {
          +ngOnInit(): void
      }
    }
  }

  class UtilityService {
      +TestingFunction(): void
  }
  package ThumderModule {
    class AppComponent {
        -document: Document
        -electronService: ElectronService
        -translate: TranslateService
        -router: Router
        +change(lang: string): void
    }
    class AppRoutingModule

  }
}

MonacoEditorComponent .up.> MonacoEditor : "Use"
FileManagerComponent .up.> FileManagement : "Use"
MachineService .up.> Int32
MachineService .up.> Float32
MachineService .up.> Double64
MachineService .up.> Registers

'ComponentModule -left-> Views
'Views -left-> Layout
'Layout -left-> Core

'ComponentModule -->
'ThumderController --> ThumderController

CoreModule ..> "@Angular"
SharedModule ..> "@Angular"
Views ..> "@Angular"
Layout ..> "@Angular"
ComponentModule ..> "@Angular"
ThumderModule ..> "@Angular"
'Shared --> "@Angular"
'Component --> "@Angular"
'Layout --> "@Angular"
'Core --> "@Angular"

'AdminComponent .up.> "@Angular"


'PageNotFoundComponent .down.> OnInit
'AdminComponent .down.> OnInit
'AuthComponent .down.> OnInit
'AsideLeftComponent .down.> OnInit
'AsideRightComponent .down.> OnInit
'Breadcrumb .down.> OnInit
'FooterAdminComponent .down.> OnInit
'FooterComponent .down.> OnInit
'MonacoEditorComponent .down.> OnInit
'AdminNavbarComponent .down.> OnInit
'AuthNavbarComponent .down.> OnInit
'FileManagerComponent .down.> OnInit
'LoginComponent .down.> OnInit
'RegisterComponent .down.> OnInit
'IndexComponent .down.> OnInit
'ForgotPasswordComponent .down.> OnInit
'LandingComponent .down.> OnInit
'ProfileComponent .down.> OnInit
'IDEComponent .down.> OnInit
'FileManagerViewComponent .down.> OnInit
'SidebarComponent .down.> OnInit
'DocsComponent .down.> OnInit


@enduml
