@startuml
!theme plain
'hide class fields
'hide class method
'hide interface fields
'hide interface method

skinparam defaultFontName "JetBrains Mono"
skinparam linetype ortho

package Core #DDDDDD {

'left
!include ./Core/Interface.puml!InterfaceMemory
!include ./Core/Manager.puml!ManagerMemory
!include ./Core/Interface.puml!InterfaceRegisters
!include ./Core/Manager.puml!ManagerRegisters

'right
!include ./Core/Interface.puml!InterfaceDataStatistics
!include ./Core/Manager.puml!ManagerStatistics
!include ./Core/Interface.puml!InterfaceBreakpoints
!include ./Core/Manager.puml!ManagerBreakpoints

'down
!include ./Core/PixiTHUMDER.puml!PixiTHUMDER_Pipeline
!include ./Core/PixiTHUMDER.puml!PixiTHUMDER_Table
!include ./Core/PixiTHUMDER.puml!Position
!include ./Core/PixiTHUMDER.puml!PixiTHUMDER_CycleClockDiagram

'center
!include ./Core/Machine.puml!MachineService

  PixiTHUMDER_Table--*Position
  PixiTHUMDER_Pipeline-->PixiTHUMDER_Table
  MachineService-->PixiTHUMDER_Pipeline
  MachineService-->PixiTHUMDER_CycleClockDiagram
  MachineService--right>ManagerRegisters
  MachineService--right>ManagerMemory
  MachineService--left>ManagerBreakpoints
  MachineService--left>ManagerStatistics

  ManagerStatistics..up|>InterfaceDataStatistics
  ManagerBreakpoints..up|>InterfaceBreakpoints
  ManagerMemory..up|>InterfaceMemory
  ManagerRegisters..up|>InterfaceRegisters
}

@enduml
