@startuml
hide class fields
hide class method
hide interface fields
hide interface method

skinparam linetype ortho

package Storage #DDDDDD {
  class StorageService {
    -storageSub: Subject<string>
    +watchStorage(): Observable<string>
    +getItem(key: string): any
    +setItem(key: string, data: any): void
    +hasItem(key: string): boolean
    +defaultDataInStorage(): void
  }
}

@enduml
