@startuml
'https://plantuml.com/class-diagram
!theme plain
'skinparam linetype ortho
'skinparam linetype polyline
'left to right direction

package Shared {

  [Guard]-down-Auth
  [Guard]-down-NoAuth

  [components]-down-PageNotFound

  [Directives]-down-AsyncAwait

  [Pipes]-down-Filter
  [Pipes]-down-Numbers
  [Pipes]-down-Objects
}

@enduml
