@startuml
'https://plantuml.com/sequence-diagram
!theme plain

autonumber

actor User
boundary InterfaceUI
participant "System\nEditor" as System
participant Server
participant "Provider" as Firebase

activate User
group#Gold User login

end

User -> InterfaceUI: Open Editor
activate InterfaceUI
User <- InterfaceUI: Show Editor
User -> InterfaceUI: Write in file
InterfaceUI -> System: Write in file
activate System

InterfaceUI <- System: Autocomplete code options
User <- InterfaceUI: Show autocomplete options
alt #LightGreen User select option
  User -> InterfaceUI: Select autocomplete option
  InterfaceUI -> System: Select autocomplete option
  System -> System: Write text
  InterfaceUI <- System: Write text
else #Pink User not select option
end


deactivate InterfaceUI
deactivate User

@enduml
