@startuml
'https://plantuml.com/sequence-diagram
!theme plain

autonumber

actor User
boundary InterfaceUI
participant "System\nEditor" as System
participant "System\nMachineService" as MachineService
participant Server
participant "Provider" as Firebase

activate User
group#Gold User login

end
User -> InterfaceUI: Open Editor
activate InterfaceUI
User <- InterfaceUI: Show Editor

InterfaceUI -> System: Analyze code
  activate System
  System -> MachineService: Analyze code
  MachineService -> Server: Analyze code
  activate Server
  MachineService <-- Server: Analyze code response
  deactivate Server
  System <-- MachineService: Analyze code response
  System -> System: Process code response
  InterfaceUI <- System: Data
  deactivate System

  alt #LightGreen Have error
    User <- InterfaceUI: Show error in code
  else #LightBlue No error in code
    User <- InterfaceUI: Show code
  else #Pink Error in response
    User <- InterfaceUI: Show notification
  end

deactivate InterfaceUI
deactivate User

@enduml
