@startuml
'https://plantuml.com/sequence-diagram
!theme plain

autonumber

actor User
boundary InterfaceUI
participant "System\nMachineService" as System
participant Server
participant "Provider" as Firebase

activate User
group#Gold User login
end

User -> InterfaceUI: Open Registers (type data)
activate InterfaceUI

InterfaceUI -> System: Select type register
activate System
InterfaceUI <- System: Show register type data
deactivate System

User <- InterfaceUI: Show Registers
deactivate InterfaceUI
deactivate User


@enduml
