@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User
boundary InterfaceUI
participant System
participant Server
participant Firebase

activate User
group#Gold User login

end
User -> InterfaceUI: Open Calculator
activate InterfaceUI
User <- InterfaceUI: Show Calculator

User -> InterfaceUI: Write number in input byte
InterfaceUI -> System: Write number in input byte
activate System
InterfaceUI <- System: Transform number to input byte
deactivate System


User -> InterfaceUI: Write number in input halfword
InterfaceUI -> System: Write number in input halfword
activate System
InterfaceUI <- System: Transform number to input halfword
deactivate System


User -> InterfaceUI: Write number in input word
InterfaceUI -> System: Write number in input word
activate System
InterfaceUI <- System: Transform number to input word
deactivate System


User -> InterfaceUI: Write number in input word Unsigned Integer
InterfaceUI -> System: Write number in input word Unsigned Integer
activate System
InterfaceUI <- System: Transform number to input word Unsigned Integer
deactivate System


User -> InterfaceUI: Write number in input float - IEEE 754 32 bits
InterfaceUI -> System: Write number in input float - IEEE 754 32 bits
activate System
InterfaceUI <- System: Transform number to input float - IEEE 754 32 bits
deactivate System


User -> InterfaceUI: Write number in input double - IEEE 754 64 bits
InterfaceUI -> System: Write number in input double - IEEE 754 64 bits
activate System
InterfaceUI <- System: Transform number to input double - IEEE 754 64 bits
deactivate System


deactivate InterfaceUI
deactivate User

@enduml
