@startuml
'https://plantuml.com/sequence-diagram
!theme plain

autonumber

actor User
boundary InterfaceUI
participant "System\nFileSystemService" as system
participant Server
participant "Provider" as Firebase

activate User
group#Gold User login

end

User -> InterfaceUI: Open file manager
activate InterfaceUI
User <- InterfaceUI: Show file manager
deactivate InterfaceUI

User -> InterfaceUI: Create file
InterfaceUI -> system: Create file
system -> Firebase: Create file

alt #LightGreen Ok
  system <-- Firebase: Create file successful
  InterfaceUI <- system: Create file successful
  User <- InterfaceUI: Create file successful
else #Pink Error
  system <-- Firebase: Create file error
  InterfaceUI <- system: Create file error
  User x<- InterfaceUI: Create file error
end

deactivate User

@enduml
