@startuml
'https://plantuml.com/sequence-diagram
'TODO
autonumber

actor User
boundary InterfaceUI
participant System
participant Server
participant Firebase

activate User
group#Gold User login

end

User -> InterfaceUI: Open profile
activate InterfaceUI
User <- InterfaceUI: Show profile
deactivate InterfaceUI

deactivate User

@enduml
