@startuml
'https://plantuml.com/sequence-diagram
!theme plain

autonumber

actor User
boundary InterfaceUI
participant System
participant Server
participant Firebase

activate User
group#Gold User login

end

User -> InterfaceUI: Open file manager
activate InterfaceUI
User <- InterfaceUI: Show file manager
deactivate InterfaceUI

User -> InterfaceUI: Delete file
InterfaceUI -> System: Delete file
System -> Firebase: Delete file

alt #LightGreen Ok
  System <-- Firebase: Delete file successful
  InterfaceUI <- System: Delete file successful
  User <- InterfaceUI: Delete file successful
else #Pink Error
  System <-- Firebase: Delete file error
  InterfaceUI <- System: Delete file error
  User x<- InterfaceUI: Delete file error
end




deactivate User

@enduml
