@startuml
'https://plantuml.com/sequence-diagram
!theme plain

autonumber

actor User
boundary InterfaceUI
participant "System \n FileSystemService" as system
participant Server
participant "Provider" as Firebase

activate User
group#Gold User login

end

User -> InterfaceUI: Open Editor
activate InterfaceUI
User <- InterfaceUI: Show Editor
deactivate InterfaceUI

User -> InterfaceUI: Save file
InterfaceUI -> system: Edit file
system -> Firebase: Edit file

alt #LightGreen Ok
  system <-- Firebase: Edit file successful
  InterfaceUI <- system: Edit file successful
  User <- InterfaceUI: Edit file successful
else #Pink Error
  system <-- Firebase: Edit file error
  InterfaceUI <- system: Edit file error
  User x<- InterfaceUI: Edit file error
end




deactivate User

@enduml
