@startuml
'https://plantuml.com/class-diagram
!theme plain
skinparam defaultFontName consolas
skinparam minClassWidth 100
skinparam conditionStyle inside
'skinparam defaultTextAlignment center
skinparam linetype polyline
skinparam linetype ortho
'left to right direction
'!include styles.puml


'class Users <<(T,red)>> {
'  Users table
'  ==
'  -uid: int
'  -email: string
'  -displayName: string
'  -photoURL: string
'  -emailVerified: boolean
'}
'
'class FileItem <<(T,red)>> {
'  FileItem table
'  ==
'  #uid: int
'  -name: string
'  -path: string
'  -content: string
'  -pathKeys: string as JSON
'  -key: string
'  -dateModified: Date
'  -size: number
'  -isDirectory: boolean
'  -hasSubDirectories: boolean
'  -thumbnail: string
'  -dataItem: string as JSON
'  'any
'}

'e01 ||..o{ e02
'one and only one <-->  zero or many


entity "Users" as e01 {
  *uid : number <<generated>>
  --
  email: text
  displayName: text
  photoURL: text
  emailVerified: boolean
}

entity "FileItems" as e02 {
  *f_id : number <<generated>>
  key : text
  pathKeys: text as JSON
  --
  description: text
  name: text
  path: text
  content: text
  dateModified: Date
  size: number
  isDirectory: boolean
  hasSubDirectories: boolean
  thumbnail: text
  dataItem: text as JSON
  e1_uid: number <<FK>>
}

e01 ||..o{ e02


@enduml
